/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
      },
      fontFamily: {
        sans: ['Inter var', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
    },
  },
  plugins: [],
  safelist: [
    'text-blue-600',
    'underline',
    'font-bold',
    'text-xl',
    'mb-2',
    'flex',
    'gap-4',
    'border',
    'border-gray-300',
    'p-2',
    'mb-2',
    'text-center',
    'w-12',
    'h-12',
    'rounded-full',
    'border-black',
    'mx-auto',
    'flex',
    'justify-center',
    'items-center',
    'w-6',
    'h-6',
    'flex-col',
    'space-y-1',
    'mt-2',
    'h-0.5',
    'bg-black',
    'max-w-5xl',
    'mb-5',
    'px-10',
    'py-5',
    'text-2xl',
    'font-bold',
    'mb-5',
    'mb-8',
    'mb-5',
    'flex',
    'items-center',
    'mb-1',
    'mr-2',
    'text-xl',
    'mb-4',
    'rounded',
    'bg-gray-100',
    'px-4',
    'py-1',
    'justify-center',
    'w-24',
    'h-24'
  ]
} 